apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCeFC399MeWTrIrKKsKm/2ydVPXxqxvVkq1aw3GOTza+FjIP3FJHwClIeNZQVQ/2qx6z+vNd2NMyg1Mx0rf/+s28S5s5c4TpYdljnlz83JEnScpstVe3eCRIW1KSbGnd+mFw07i8xERBYTadWvMF4vmFJfh8JGXkvAlaNcF/uGho/TlfAAyIKhwnV6RQZMTBQMXLF/jgOfAdTEhesWBQKjMkJD8sgU6DR+gIf6gflVClUJ6tERg8YKvAgRn5m9XiCJvVRhK/5DlxZoXD6VEhBMTRCNJ+fq7UJnm90uuhcJsODIGBhEzeyBCAtR7fyiYdU0o4ZurBVE+iHuAvCzujH9e4aOeA1PAnEyVdSrkuE8TXEvKzkTGG4PcyHqRguJGWDQxvRxm6OM8lZuD+m9dTQiB97WgT/9MI7ukHTiQXqbYWW0BVls5ylBK+fhGbJxktGQ96XW1sGu0rG+22T5cJWff7v8wMjBGLRz0B28Cr/dr0CrAUZGX3zoIOXn3KrlI2OlnUV18/BLfT4YHW2NrnfZWz/1u/oCCYydqPBrTNPfh55ktcjIVDhjrXkR2rhcnAJIak9qGoV9KXtZnk0vN/QJpRcxtEoNRIF55yezsTMR9gQpGinn5QRtH0zCBaRtWTgPJrgLK+3rR09gOM7pC9jTFA5FWpDUS3CuJjXlUGEHYIN+S1GNieI1vg2vYeerM7CbfVcZVrTCzC/iIcsetrPMYyUMV9RWPYWaO4kAspxQgnkbjGq651lVswg9+k+T0YulzOIQYvE9xRHOarDdMbkIFP/o8YvSCOpuq24MXZMlJDiL+wh5XSx5o5CiOJ89D2ITCMFUPVyx2oI1xaXeQrhAAfWtuSLS6VsJXHKxHiy80Y/KV
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson
